### ISSUE TITLE
Cannot send POST request to REST proxy

### ISSUE THREAD

**Issue by cakriwut** [nonblocking/mashroom#104]
I have REST api that provides CRUD service and store to database. 
I follow the example in "mashroom-portal-demo-rest-proxy-app" , and so far I only managed to perform GET request to the REST api.

When I tried to perform POST request to REST api from the frontend, I can see HTTP error 403 in the traffic. 
I have checked the http proxy plugin configuration allowed all HTTP verbs.

Any ideas how can I solve this problem? Currently only GET request is successfully proxied by Mashroom.

**Comment by nonblocking** [comment]
You have most probably the CSRF protection active, which means all request must contain the CSRF token embedded on the page. You should the error "Rejecting request without CSRF token" in the server logs.

Just remove the dependency @mashroom/mashroom-csrf-protection or add the toke like so:
```
   headers['X-CSRF-Token'] = document.querySelector('meta[name="csrf-token"]');
```

**Comment by cakriwut** [comment]
Thanks - X-CSRF-Token was missing.
