### ISSUE TITLE
Need to get extraData form OpenID Connect Security Provider

### ISSUE THREAD

**Issue by MinHtet-O** [nonblocking/mashroom#108]
I need to access the extraData provided from my external Identity Provider. I can see the log like this when the user is authenticated. But those extraData are not passed  to **portalAppSetup** object in my portal-app2 plugin.

This is the log when the user is authenticated. I see the extraData here.
```
2023-02-01T16:54:18.292 DEBUG Z8RrOTuGL0vb1C6sg2ROIu9okEHF31cB ::1 Chrome 109.0.0.0 null mashroom.security.provider.openid.connect - User successfully authenticated: {
  username: 'minhtetoo',
  displayName: 'Min Htet Oo',
  email: 'minhtetoo@s2t.ai',
  pictureUrl: null,
  extraData: { given_name: 'Min', Department: 'Information Technology' },
  roles: [],
  secrets: null
}
```

This is the portalAppSetup object. I don't see the extraData.

[https://drive.google.com/file/d/16l9aRbpNUHmsGK0CAA8CRTyz9IzKRZd4/view?usp=share_link](url)

This is the setting for Mashroom OpenID Connect Security Provider.

```
    "Mashroom OpenID Connect Security Provider": {
      issuerDiscoveryUrl: `${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/.well-known/uma2-configuration`,
      clientId: KEYCLOAK_CLIENT_ID,
      clientSecret: KEYCLOAK_CLIENT_SECRET,
      redirectUrl: `${PORTAL_URL}/openid-connect-cb`,
      rolesClaim: "roles",
      adminRoles: ["mashroom-admin"],
      extraDataMapping: {
        given_name: "given_name",
        Department: "department",
      },
    },
```

Do I need additional configuration for this? Is there any way to access those extra data inside plugin?

**Comment by nonblocking** [comment]
Yes, you have to add the mashroom-portal-app-user-extradata plugin: https://github.com/nonblocking/mashroom/tree/master/packages/plugin-packages/mashroom-portal-app-user-extradata - which copies the extraData properties to the Portal App user (which are separate things).
