### ISSUE TITLE
way to modify the req?

### ISSUE THREAD

**Issue by Aftab-Fury** [nonblocking/mashroom#116]
We do have a way to modify the response, using interceptor, but can we modify the req body? as it's a stream ? 

    async interceptResponse(targetUri: string, existingHeaders: Readonly<HttpHeaders>, targetResponse: IncomingMessage, clientRequest: ExpressRequest, clientResponse: ExpressResponse) {
        let body = [];
        targetResponse.on('data', function (chunk) {
            body.push(chunk);
        });
        targetResponse.on('end', function () {
            body = Buffer.concat(body).toString();
            console.log("Response from proxied server:", body);
            clientResponse.json({ success: true });
        });

        // NOTE: if you "await" the end event you have to call targetResponse.resume() here
        //  because the interceptor pauses the stream from the target until all interceptors are done

        return {
            responseHandled: true
        };
    }

**Comment by Aftab-Fury** [comment]
I went through the source code of ProxyImplNodeStreamAPI.ts as well, and once the request body has been read from the req stream, it's not possible to "put" it back into the req object in a way that the rest of application can use it like it was part of the original request. This is because req in an HTTP server context is a read-only stream representing the incoming HTTP request. Once data has been consumed from a stream, it doesn't go back into the stream. Please correct me if I am wrong.

**Comment by nonblocking** [comment]
You are right, there is no way to directly modify request or response (like in your example above).

But we plan to allow to pass stream transformers (https://nodejs.org/api/stream.html#duplex-and-transform-streams) in the future.

**Comment by Aftab-Fury** [comment]
> You are right, there is no way to directly modify request or response (like in your example above).
> 
> But we plan to allow to pass stream transformers (https://nodejs.org/api/stream.html#duplex-and-transform-streams) in the future.

Awesome, what I am now is creating new streams.

**Comment by nonblocking** [comment]
In the upcoming Mashroom version 2.6. you can define stream transfomers like so:

```
export default class MyInterceptor implements MashroomHttpProxyInterceptor {
      async interceptRequest(targetUri) {
          if (targetUri.startsWith('https://my-backend-server.com')) {
              return {
                  streamTransformers: [
                      crypto. createCipheriv(/* ... */),
                  ],
              };
          }
      }
      async interceptResponse(targetUri, existingHeaders) {
          if (targetUri.startsWith('https://my-backend-server.com') && existingHeaders['content-encoding'] === 'gzip') {
              return {
                  streamTransformers: [
                     crypto. createDecipheriv(/* ... */),
                  ],
              };
          }
      }
  }
```

**Comment by Aftab-Fury** [comment]
Awesome, Thank you.

**Comment by Aftab-Fury** [comment]
> In the upcoming Mashroom version 2.6. you can define stream transfomers like so:
> 
> ```
> export default class MyInterceptor implements MashroomHttpProxyInterceptor {
>       async interceptRequest(targetUri) {
>           if (targetUri.startsWith('https://my-backend-server.com')) {
>               return {
>                   streamTransformers: [
>                       crypto. createCipheriv(/* ... */),
>                   ],
>               };
>           }
>       }
>       async interceptResponse(targetUri, existingHeaders) {
>           if (targetUri.startsWith('https://my-backend-server.com') && existingHeaders['content-encoding'] === 'gzip') {
>               return {
>                   streamTransformers: [
>                      crypto. createDecipheriv(/* ... */),
>                   ],
>               };
>           }
>       }
>   }
> ```

Awesome, Thank you.
