### ISSUE TITLE
Dynamic resizing of Apps on a page

### ISSUE THREAD

**Issue by devexter** [nonblocking/mashroom#119]
Is there any way to give an App on a page focus and expand it to fill the App panel?

Then allow it to be defocused and return to it's original designated position in the App panel?

**Comment by nonblocking** [comment]
No, but should be simple to implement this in the theme or layout template. Alternatively you might consider using the Fullscreen API to just blow up the App to fullscreen.

**Comment by devexter** [comment]
Thanks, I'll look into those.
