### ISSUE TITLE
Is there a way to define sites and pages via config or programatcally

### ISSUE THREAD

**Issue by devexter** [nonblocking/mashroom#120]
I want to create a default set of sites and pages to display on initial portal deployment.

The portal comes with a demo site and pages, is it possible for me to use a similar mechanism?

**Comment by nonblocking** [comment]
It depends on the storage provider you use. 

- filestore: Just deploy the data/storage folder together with the server. I suggest to even keep the files there under version control, thats how we do it in most of our customer projects.
- db storage (mongo): You could use any plugin bootstrap to initialize the DB or use some route to trigger the load manually, like here: https://github.com/nonblocking/mashroom-content/tree/master/test/test-server1/plugins/init
