### ISSUE TITLE
Global static app

### ISSUE THREAD

**Issue by cakriwut** [nonblocking/mashroom#124]
What is the recomended strategy to create app plugin which will be available in all pages?

Currently the user profile is statically implemented in themes. I would like to explore having a startup job, that allow us to specify different implementation of user profile menu without having to create different themes.

How can I do that?

**Comment by nonblocking** [comment]
I'm not sure if I understand your requirement correctly, but if you want to load different app for different user groups in your theme you could do something like this in your theme template:

```html
<body>
   <div id="profile-app-container"></div>
   // ...
   <script>
       const profileApp = // determine from user.roles, depends on template language
       document.addEventListener('DOMContentLoaded', () => 
            MashroomPortalServices.portalAppService.loadApp('profile-app-container', profileApp)
       );
   </script>
</body>
```

**Comment by cakriwut** [comment]
Thanks, I could use this suggestion. Which mean, I could also use the theme config to further configure the theme behaviour.
