### ISSUE TITLE
Allow to use namespace in bootstrap function

### ISSUE THREAD

**Issue by cakriwut** [nonblocking/mashroom#125]
Currently the bootstrap register global function such as

```ts
const bootstrap: MashroomPortalAppPluginBoostrapFunction ...

(global as any).appboostrap = boostrap;
```
This can lead into conflict when two or more plugin with the same name are loaded.  Although we can use naming convention, but is it possible to support using namespace in bootstrap? Currently it is not possible to do something like this

```ts
const bootstrap: MashroomPortalAppPluginBoostrapFunction ...

(global as any).appboostrap = boostrap;
```ts
if(!(global as any).namespace) {
    (global as any).namespace = {}
}

(global as any).namespace.appbootstrap = bootstrap
```

**Comment by nonblocking** [comment]
Yes, we considered this, but it actually wouldn't improve things a lot since namespaces could also conflict. I suggest to do something like 

```ts
(global as any).__<namespace>__appbootstrap = bootstrap;
```

With \<namespace\> being the name of the team of the business unit.
