### ISSUE TITLE
Data remains in old data when I change mashroom.json default Theme

### ISSUE THREAD

**Issue by burakakca** [nonblocking/mashroom#17]
I'm using mashroom portal quickstart and when i change the defaultTheme nothing happens
But when i delete data folder and restart then example theme comes

**Comment by nonblocking** [comment]
The *defaultTheme* property in mashroom.json is just a fallback Theme and preselected when you are going to create a new Site. For an existing Site you have to change the default site in the Admin UI.

**Comment by burakakca** [comment]
Thanks for the quick turnaround
![image](https://user-images.githubusercontent.com/56919004/84570049-5836b700-ad93-11ea-8212-58f04ec55fd5.png)
Do you mean that ?

**Comment by nonblocking** [comment]
Yes! But you are right, it could make sense to have an option here to just inherit the default theme from the server config. I think about it.

**Comment by burakakca** [comment]
I agree . Thanks again
