### ISSUE TITLE
Caching in PortalAppController#getPortalAppSetup breaks dynamic loading of multiple instances of the same app

### ISSUE THREAD

**Issue by mheimschild** [nonblocking/mashroom#89]
There are pages where the same app needs to be loaded more than once with different appId. Caching introduced for portalAppSetup prevents browser from obtaining fresh appSetup with newly generated appId

**Comment by nonblocking** [comment]
For the same user the response should always be the same. If a page contains more than one instance of an app the portalAppInstanceId must be different and so the path. So, I'm not sure how this could break someting.

**Comment by mheimschild** [comment]
I meant pages where apps are loaded on the fly multiple times like dynamic cockpits
